### ISSUE TITLE
Unable to detect the screen size if wrapped with 'watch'?

### ISSUE THREAD

**Issue by 097115** [Gbox4/tstock#23]
When using with [`watch`][0], like `watch --interval 20 tstock btc`, `tstock` seems to fail while detecting the screen size:

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.9/bin/tstock", line 8, in <module>
        sys.exit(main())
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tstock/core.py", line 428, in main
        opts = parse_args(parser)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/tstock/parse.py", line 47, in parse_args
        t = os.get_terminal_size()
    OSError: [Errno 25] Inappropriate ioctl for device

[0]: https://en.wikipedia.org/wiki/Watch_(command)

**Comment by Gbox4** [comment]
Ok, it should be fixed in https://github.com/Gbox4/tstock/commit/1e58133cea0d1be49beb5965ba6ab4b8321263e3. Make sure to run `watch` with the `-c` flag to properly interpret the ANSI coes: `watch -c --interval 20 tstock btc`.
